version: '3.8'

services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    working_dir: /app
    command: npx ts-node-dev --respawn src/index.ts
    environment:
      - DATABASE_URL=postgres://ecommerce:secret@postgres:5432/ecommerce

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules    # preventing host node_modules cover the one in Docker
    ports:
      - "3000:3000"
      
    working_dir: /app
    command: npm run dev
    depends_on:
      - backend
