version: '3.8'

services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./ldrvecommerce
    ports:
      - "9000:9000"
    environment:
      DATABASE_URL: postgres://ecommerce:secret@database:5432/medusa-ldrvecommerce
    depends_on:
      - postgres
    volumes:
      - ./ldrvecommerce:/app
    restart: on-failure


  frontend:
    build:
      context: ./ldrvecommerce-storefront
    ports:
      - "8000:8000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_MEDUSA_BACKEND_URL: http://backend:9000
    volumes:
      - ./ldrvecommerce-storefront:/app
